# Generated by Django 3.2.16 on 2023-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0002_accountholder_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
