# Generated by Django 3.2.16 on 2023-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0007_auto_20230119_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
